# Generated by Django 5.2.9 on 2025-12-29 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('pays', models.CharField(choices=[('cameroun', 'Cameroun'), ('congo', 'Congo'), ('rd-congo', 'RD Congo'), ('senegal', 'Sénégal'), ('cote-ivoire', "Côte d'Ivoire"), ('ghana', 'Ghana'), ('nigeria', 'Nigeria'), ('kenya', 'Kenya'), ('benin', 'Bénin'), ('mauritanie', 'Mauritanie'), ('guinee', 'Guinée Conakry'), ('afrique-sud', 'Afrique du Sud'), ('somalie', 'Somalie'), ('egypte', 'Égypte'), ('autre', 'Autre pays africain')], max_length=50, verbose_name='Pays')),
                ('organisation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisation')),
                ('type_demande', models.CharField(choices=[('projet', 'Soumettre un projet'), ('adhesion', 'Devenir membre'), ('partenariat', 'Proposition de partenariat'), ('financement', 'Opportunité de financement'), ('media', 'Demande média/presse'), ('stage', 'Stage/Bénévolat'), ('information', "Demande d'information"), ('autre', 'Autre')], max_length=50, verbose_name='Type de demande')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('archive', 'Archivé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('repondu', models.BooleanField(default=False, verbose_name='Répondu')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('notes_internes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('pays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_desabonnement', models.DateTimeField(blank=True, null=True, verbose_name='Date de désabonnement')),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
